/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        HttpClient classUnderTest = new HttpClient();
        //assertNotNull(classUnderTest.someMethod(), "returns some value");
    }
}
